src/java/Bean.java
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import university.*;


public class Bean {
private String ID;
private String PASS;
private String firstName;
private String lastName;
private String gender;
private String dob;
private String address;
private String phoneNumber;
private String emailID;
Student std=new Student();
    /** Creates a new instance of Bean */
    public Bean() {
    }
    public String Action()
    {
      StringBuilder fName=new StringBuilder();
      StringBuilder lName=new StringBuilder();
      StringBuilder gndr=new StringBuilder();
      StringBuilder db=new StringBuilder();
      StringBuilder add=new StringBuilder();
      StringBuilder ph=new StringBuilder();
      StringBuilder email=new StringBuilder();
    ApplicationContext apc = new ClassPathXmlApplicationContext("university/spring-hibernate.xml");  
    BeanDAO bhp=(BeanDAO)apc.getBean("beanDao");
      String uname=getID();
      String pass=getPASS();
      boolean b=false;
      List<Student> students=new ArrayList<Student>();
      students=bhp.getStudent();
      for(Iterator it=students.iterator();it.hasNext();)
        {
           std=(Student)it.next();
           if((std.getUserid().toString().equals(uname))&& (std.getPassword().toString().equals(pass)))
            {
               b=true;
               fName.append(std.getFirstname().toString());
               lName.append(std.getLastname().toString());
               gndr.append(std.getGender().toString());
               db.append(std.getDob().toString());
               add.append(std.getAddress().toString());
               ph.append(std.getPhone().toString());
               email.append(std.getEmail().toString());
               setValues(fName, lName, gndr, db, add, ph, email);
               break;
             }
            else
                b=false;
         }
      if (b==true)
      {
         return "student";
        }
      else
         return "error";
    }

    public void setValues(StringBuilder fName, StringBuilder lName, StringBuilder gndr, StringBuilder db, StringBuilder add, StringBuilder ph, StringBuilder email)
    {
       setFirstName(fName.toString());
       setLastName(lName.toString());
       setGender(gndr.toString());
       setDob(db.toString());
       setAddress(add.toString());
       setPhoneNumber(ph.toString());
       setEmailID(email.toString());
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }
    public String getPASS() {
        return PASS;
    }
    public void setPASS(String PASS) {
        this.PASS = PASS;
    }

    /**
     * @return the firstName
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * @param firstName the firstName to set
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * @return the lastName
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * @param lastName the lastName to set
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @return the gender
     */
    public String getGender() {
        return gender;
    }

    /**
     * @param gender the gender to set
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * @return the dob
     */
    public String getDob() {
        return dob;
    }

    /**
     * @param dob the dob to set
     */
    public void setDob(String dob) {
        this.dob = dob;
    }

    /**
     * @return the address
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address the address to set
     */
    public void setAddress(String address) {
        this.address = address;
    }
    /**
     * @return the phoneNumber
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @param phoneNumber the phoneNumber to set
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * @return the emailID
     */
    public String getEmailID() {
        return emailID;
    }

    /**
     * @param emailID the emailID to set
     */
    public void setEmailID(String emailID) {
        this.emailID = emailID;
    }
}

src/java/CourseDetailsBean.java
import university.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.faces.component.html.HtmlOutputText;
import javax.faces.event.ValueChangeEvent;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;


public class CourseDetailsBean
{
    private String CourseName;
    private HtmlOutputText CourseId, CourseDuration, CourseEligibility, CourseFee;  
    public CourseDetailsBean() {   
    }
    Coursedetails course=new Coursedetails();
    public void CourseDetailsAction(ValueChangeEvent vce)
    {
      String cName = vce.getNewValue().toString();
      StringBuilder cID = new StringBuilder();
      StringBuilder cDuration=new StringBuilder();
      StringBuilder cEligibility=new StringBuilder();
      StringBuilder cFee=new StringBuilder();
      performLookup(cID, cName, cDuration, cEligibility, cFee);
      getCourseId().setValue(cID.toString());
      getCourseDuration().setValue(cDuration.toString());
      getCourseEligibility().setValue(cEligibility.toString());
      getCourseFee().setValue(cFee.toString());

    }
    void performLookup(StringBuilder cID, String cName, StringBuilder cDuration, StringBuilder cEligibility, StringBuilder cFee)
        {
           ApplicationContext apc = new ClassPathXmlApplicationContext("university/spring-hibernate.xml");
           CourseDetailsDAO helper=(CourseDetailsDAO)apc.getBean("courseDetailsDao");
           List<Coursedetails> courses=new ArrayList<Coursedetails>();
           courses=helper.getcourseByName(cName);
           Iterator iterator;
           iterator=courses.iterator();
           while(iterator.hasNext())
           {
             course=(Coursedetails)iterator.next();
           }
            cID.append(course.getCourseid().toString());
            cDuration.append(course.getCourseduration().toString());
            cEligibility.append(course.getCourseeligibility().toString());
            cFee.append(course.getCoursefee().toString());
}

    public String getCourseName()
    {
        return CourseName;
    }
    public void setCourseName(String CourseName)
    {
        this.CourseName = CourseName;
    }
    public HtmlOutputText getCourseId()
    {
        return CourseId;
    }
    public void setCourseId(HtmlOutputText CourseId)
    {
        this.CourseId = CourseId;
    }
    public HtmlOutputText getCourseDuration()
    {
        return CourseDuration;
    }
    public void setCourseDuration(HtmlOutputText CourseDuration)
    {
        this.CourseDuration = CourseDuration;
    }
    public HtmlOutputText getCourseEligibility()
    {
        return CourseEligibility;
    }
    public void setCourseEligibility(HtmlOutputText       
    CourseEligibility)
    {
        this.CourseEligibility = CourseEligibility;
    }
    public HtmlOutputText getCourseFee()
    {
        return CourseFee;
    }
    public void setCourseFee(HtmlOutputText CourseFee)
    {
        this.CourseFee = CourseFee;
    }
}

web/AboutUs.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <style>
            table, tr {
                border: 1px solid white;
                }
        </style>
        <title>Grant University</title>
    </h:head>
    <h:body>
        <ui:composition template="BaseTemplate.xhtml">
            <ui:define name="body">
                <p style="color: darkblue; font-size:20pt">
                   <b>UNIVERSITY</b> <br/> </p>   
               <p style="font-size:15pt">
Grant University, was established in the year 1976 with a specific objective-
<br/><br/> "To establish and incorporate a teaching-cum-affiliating University at California for the encouragement of interdisciplinary higher education and research with special emphasis on studies of Life Sciences and Environmental and Ecological Sciences". During the last 26 years of its existence, the University has achieved a remarkable degree of success in its expansion programs, infrastructural developments, and academic excellence.
<br/><br/>There are 66 Boards of Studies for developing and designing courses in different disciplines.

<br/><br/>In addition to the main Campus, there are two satellite campuses - Regional Centre running post-graduate teaching at California and National Law College at Texas.

<br/><br/> As an affiliating University, it has 126 institutions and colleges under its control with an enrolment of about 170,000 students.

<br/><br/> Affiliated institutes of Grant University consist of a number of Engineering Colleges, Computer and Management Studies institutes, and Pharmaceutical Colleges.
</p>
            </ui:define>
        </ui:composition>

    </h:body>
</html>

web/Admissions.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <style>
            table, tr {
                border: 1px solid white;
                }
        </style>
        <title>Grant University</title>
    </h:head>
    <h:body>
       <ui:composition template="BaseTemplate.xhtml">
            <ui:define name="body">
                <p align="center" style="color:darkblue;font-size:20pt"> Admission details for various courses: </p>
    <br/>
    <table border="1" width="70%" align="center" style="height: 100px">
    <tr>
      <td align="center"><b>S.No.</b></td>
      <td align="center"><b>Courses Offered</b></td>
      <td align="center"><b>Admissions Starting Date</b></td>
      <td align="center"><b>Admissions Ending Date</b></td>
        </tr>
        <tr>
          <td align="center"> 1 </td>
          <td align="center">Science</td>
          <td align="center">30/05/2011</td>
          <td align="center">29/06/2011</td>
        </tr>
        <tr>
         <td align="center">2</td>
         <td align="center">Law</td>
      <td align="center">20/05/2011</td>
      <td align="center">14/06/2011</td>
    </tr>
    <tr>
     <td align="center">3</td>
       <td align="center">Business Management</td>
       <td align="center">15/05/2011</td>
       <td align="center">10/06/2011</td>
    </tr>
    <tr>
     <td align="center">4</td>
     <td align="center">Medical</td>
     <td align="center">25/05/2011</td>
     <td align="center">10/06/2011</td>
    </tr>
   </table>
            </ui:define>
        </ui:composition>

    </h:body>
</html>

web/BaseTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:lc="http://xmlns.jcp.org/jsf/composite/LoginControl">
    <h:head>
        <title>Grant University</title>
        <link href="./resources/ExternStyleSheet.css" rel="stylesheet" type="text/css" />
<style>
            table, tr {
                border: 1px solid white;
                }
</style>

    </h:head>
    <h:body>
        <table border="0" bgcolor="#808080" align="top" width="100%" style="height:100px">
  <tr>
   <td bgcolor="#000080" align="center">
     <p style="font-size: 38pt; color: #ffffff; font-family: Arial Rounded MT Bold">GRANT UNIVERSITY</p> 
   </td>
   <td bgcolor="666699" align="left" width="180">     <img alt=""  src="Images/education.jpg" width="250" height="170" align="right"/>
   </td>
  </tr>
</table>
<table bgcolor="white"  border="1"  align="top" width="100%" style="height:470px">
<tr>
   <td bgcolor="#000080" width="20%" valign="top" align="center">
     <br/>   <br/>
     <h:form>
      <h:commandLink styleClass="fFormat" action="index" value="Home"></h:commandLink>
      <br/>   <br/>
      <h:commandLink styleClass="fFormat" action="AboutUs" value="About Us"></h:commandLink>
      <br/>   <br/>
      <h:commandLink styleClass="fFormat" action="Registration" value="Registration"></h:commandLink>
      <br/>   <br/>
      <h:commandLink styleClass="fFormat" action="Admissions" value="Admissions"></h:commandLink>
      <br/>   <br/>
      <h:commandLink styleClass="fFormat" action="Contacts" value="Contact Us"></h:commandLink>
      <br/><br/>
      <h:commandLink styleClass="fFormat" action="CourseDetails" value="Course Details"></h:commandLink>
     </h:form>
     <lc:LoginControl userName="#{bean.ID}" password="#{bean.PASS}" submitValue="Submit" resetValue="Reset"/>
</td>
       <!-- Page specific content starts here  -->
  <td width="85%" valign="top" bgcolor="white">
      <ui:insert name="body"/>
  </td>
</tr>
</table>

    </h:body>
</html>

web/Contacts.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <style>
            table, tr {
                border: 1px solid white;
                }
        </style>
        <title>Grant University</title>
    </h:head>
    <h:body>
       <ui:composition template="BaseTemplate.xhtml">
            <ui:define name="body">
               <br/><p align="center" style="color: darkblue; font-size: 20pt">Contact Us </p>
                    <br/><br/><table border="0" width="60%" style="height:100px" align="center">
 <tr>
    <td>Address</td>
    <td width="20px">:</td>
    <td>214 Verbo Street, California</td>
 </tr>
 <tr>
   <td>Phone</td>
   <td>:</td>
   <td>009919214562</td>
 </tr>
 <tr>
    <td>Fax</td>
    <td>:</td>
    <td>009919214562</td>
 </tr>
 <tr>
  <td>E-mail</td>
  <td>:</td>
  <td>info@grantuniversity.com</td>
 </tr>
</table>
            </ui:define>
        </ui:composition>

    </h:body>
</html>

web/CourseDetails.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <style>
table, tr {
    border: 1px solid white;
          }
    </style>

        <title>Course Details</title>
    </h:head>
    <h:body>
           <ui:composition template="BaseTemplate.xhtml">
            <ui:define name="body">
           <p style="font-size:12pt">
                     <br/>
                     <p style="color: darkblue; font-size:20pt" align="center">
                          <b>Course Details </b>
                    </p>
                     <br/><br/>
                     <table border="0" width="50%" align="center">
                         <h:form>
                         <tr>
                             <td>Select Course Name</td>
                         <td>:</td>
                         <td align="center">
                             <h:selectOneMenu
                                     id="cname" value="#{courseDetailsBean.courseName}" valueChangeListener="#{courseDetailsBean.CourseDetailsAction}" onchange="this.form.submit()">
                                     <f:selectItem itemValue="" itemLabel="" />
                                     <f:selectItem itemValue="Science" itemLabel="Science" />
                                  <f:selectItem itemValue="Law" itemLabel="Law" />
                                  <f:selectItem itemValue="Medical" itemLabel="Medical" />
                                    <f:selectItem itemValue="Management" itemLabel="Management" />
                                 </h:selectOneMenu>
                             </td>
                         </tr>
                             <tr>
                                 <td>
                                     <br/>
                                     Course Id
                                 </td>
                                 <td>
                                     <br/>
                                 :
                             </td>
                                 <td align="center">
                                     <br/>
                                     <h:outputText id="cid" binding="#{courseDetailsBean.courseId}"/>
                                 </td>
                             </tr>
                             <tr>
                                 <td>
                                     Course Duration
                                 </td>
                                 <td>
                                 :
                             </td>
                                 <td align="center">
                                     <h:outputText id="cdur" binding="#{courseDetailsBean.courseDuration}"/>
                                 </td>
                             </tr>
                             <tr>
                                 <td>
                                     Course Eligibility
                                 </td>
                                 <td>
                                 :
                             </td>
                                 <td align="center">
                                     <h:outputText id="celig" binding="#{courseDetailsBean.courseEligibility}"/>
                                 </td>
                             </tr>
                             <tr>
                                 <td>
                                     Course Fee
                                 </td>
                                 <td>
                                 :
                             </td>
                                <td align="center">
                                     <h:outputText id="cfee" binding="#{courseDetailsBean.courseFee}"/>
                                 </td>
                             </tr>
                         </h:form>
                     </table>
                    </p>
          </ui:define>
       </ui:composition>


    </h:body>
</html>

web/LoginError.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:lc="http://xmlns.jcp.org/jsf/composite/LoginControl">
    <h:head>
        <style>
            table, tr {
                border: 1px solid white;
                }
        </style>
        <title>Login Failed</title>
        <link href="./resources/ExternStyleSheet.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
        <table border="0" bgcolor="#808080" align="top" width="100%" style="height:100px">
            <tr>
                <td bgcolor="#000080" align="center"><p style="color:#FFF0F5">
                        <p style="font-size: 24pt; color: #ffffff; font-family: sans-serif">GRANT UNIVERSITY</p> 
                    </p>
        
                </td>
                <td bgcolor="666699" align="left" width="180">
                    <img alt="" src="Images/education.jpg" width="180" height="120" align="right"/>
                </td>
            </tr>
        </table>
        <table bgcolor="white" border="1"  align="top" width="100%" style="height:470px">
        <tr>
        <td bgcolor="#000080" width="20%" valign="top" align="center">
          <lc:LoginControl userName="#{bean.ID}" password="#{bean.PASS}" submitValue="Submit" resetValue="Reset"/>
      </td>
      <td width="85%" valign="top" bgcolor="white">
        <br/>
        <p style="size:15pt; color:red">
          <b>Incorrect User Name and Password </b>
          <br/>
          <h:form><h:commandButton styleClass="button" value="Home" action="index"/></h:form>
        </p>
      </td>
     </tr>
   </table>
  </h:body>
</html>

web/Registration.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <style>
            table, tr {
                border: 1px solid white;
                }
        </style>
        <title>Grant University</title>
          <link href="./resources/ExternStyleSheet.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
       <ui:composition template="BaseTemplate.xhtml">
            <ui:define name="body">
                <p align="center" style="color: darkblue; font-size: 20pt"> Registration Form </p> <br/>
  <table bgcolor="black" cellpadding="12px" border="1" width="60%" align="center"  style="height:120px">
     <tr>
       <td bgcolor="white">
         <table border="0" width="100%" bgcolor="white" align="center" style="height: 100px">
<h:form>
     <tr>
              <td>First Name:</td>
              <f:ajax event="change" render="nameError">
              <td><h:inputText value="#{registrationForm.firstName}" id="fName" required="true" requiredMessage="You must enter the first name" validator="#{registrationForm.validateName}"/>
    <h:message for="fName" id="nameError" style="color:red"/></td></f:ajax>
     </tr>
    <tr>
               <td>Last Name:</td>
               <td><h:inputText value="#{registrationForm.lastName}" id="lName" required="true"  requiredMessage="You must enter the last name"/>
<h:message for="lName" style="color:red"/></td>	
    </tr>
     <tr>
               <td>Select Gender:</td>
               <td><h:selectOneRadio value="#{registrationForm.gender}" id="gender" required="true" requiredMessage="You must select the gender">
                     <f:selectItem itemValue="m" itemLabel="Male" />
                    <f:selectItem itemValue="f" itemLabel="Female" />
                    </h:selectOneRadio>
                   <h:message for="gender" style="color:red"/>                  
               </td>
	</tr>
     <tr>
               <td>Date of birth:</td>
               <td><h:inputText id="dob" required="true" requiredMessage="You must enter date of birth" converterMessage="Enter DOB in MM/DD/YY format" value="#{registrationForm.dateofBirth}">
<f:convertDateTime pattern="MM/dd/yy" type="date"/>
</h:inputText>
<h:message for="dob" style="color:red"/></td>
	</tr>
     <tr>
               <td>Address:</td>
               <td><h:inputTextarea rows="3" value="#{registrationForm.address}" id="add" required="true" requiredMessage="You must enter the address"/>
	<h:message for="add" style="color:red"/></td>
     </tr>
     <tr>
               <td>Phone number:</td>
               <td><h:inputText value="#{registrationForm.contactNumber}" id="ph" required="true" requiredMessage="You must enter a contact number">
<f:validateRegex pattern="[0-9]{2}-+[0-9]{3}-+[0-9]{8}"/>
</h:inputText>
<h:message for="ph" style="color:red"/></td>
	</tr>
     <tr>
               <td>E-mail Id:</td>
               <td><h:inputText value="#{registrationForm.emailID}" id="email" required="true" requiredMessage="You must enter the e-mail Id" validator="#{registrationForm.validateEmail}" validatorMessage="Invalid e-mail Id"/>
<h:message for="email" style="color:red"/></td>
	</tr>
    <tr>
                            <td>Course:</td>
                            <td><h:selectOneMenu id="cname" value="#{registrationForm.course}">
                          <f:selectItem itemValue="NULL" itemLabel="Select a Course" />
                          <f:selectItem itemValue="A-101" itemLabel="Computer Science" />
                          <f:selectItem itemValue="A-105" itemLabel="Law" />
                          <f:selectItem itemValue="A-110" itemLabel="Medical" />
                          <f:selectItem itemValue="A-115" itemLabel="Management" />
                        </h:selectOneMenu>
                            </td>
</tr>

     <tr>
               <td>User Id:</td>
               <td><h:inputText id="uid" value="#{registrationForm.userID}" required="true" requiredMessage="You must enter user Id" validatorMessage="User Id should be at least 6 characters long">
<f:validateLength minimum="6"/>
</h:inputText>
<h:message for="uid" style="color:red"/></td>
     </tr>

     <tr>
               <td>Password:</td>
               <td><h:inputSecret id="pass" size="12" value="#{registrationForm.password}" required="true" requiredMessage="You must enter the password" validatorMessage="Password must be minimum 5 characters long" validator="#{registrationForm.validateFinalPassword}">
<f:validateLength minimum="5"/>
</h:inputSecret>
<h:message for="pass" style="color:red"/></td>
     </tr>

     <tr>
               <td>Confirm password:</td>
               <td><h:inputSecret size="12" value="#{registrationForm.confirmPassword}" id="cpass" required="true" requiredMessage="You must confirm the password" validator="#{registrationForm.validateCPassword}"/>
<h:message for="cpass" style="color:red"/></td>
     </tr>
     <tr>
               <td align="right"><br/>
                     <h:commandButton value="Submit" action="#{registrationForm.submitAction}"/>
               </td>
               <td align="left"><br/>
                     <h:commandButton value="Reset" immediate="true" action="Registration"/>
               </td>
	</tr>
    <tr>
    <p><h:outputText style="color: red" value="#{registrationForm.userIdError}" /></p>
</tr>

    </h:form>
    </table>
    </td>
    </tr>
    </table>
        </ui:define>
       </ui:composition>

    </h:body>
</html>

web/Success.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Welcome</title>
        <link href="./resources/ExternStyleSheet.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
               <table border="0" bgcolor="#808080" align="top" width="100%" style="height:100px">
            <tr>
                <td bgcolor="#000080" align="center">
<p style="font-size: 38pt; color: #ffffff; font-family: Arial Rounded MT Bold">GRANT UNIVERSITY</p>
                </td>
                <td bgcolor="666699" align="left" width="180">     <img alt=""  src="Images/education.jpg" width="180" height="160" align="right"/>
                 </td>
            </tr>
        </table>
        <h2>Welcome &nbsp;
            <h:outputText id="o1" value="#{registrationForm.firstName}"/>&nbsp;
        <h:outputText id="o2" value="#{registrationForm.lastName}"/> </h2>
        <h2>
            You have successfully registered with our website.<br/>
            Your User ID is:&nbsp;<h:outputText id="o3" value="#{registrationForm.userID}"/>
        </h2>
<table><tr><td align="center"><h:form><h:commandButton styleClass="button" value="Home" action="index"/></h:form></td></tr></table>

    </h:body>
</html>

web/WEB-INF/jsp/index.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Welcome to Spring Web MVC project</title>
    </head>

    <body>
        <p>Hello! This is the default welcome page for a Spring Web MVC project.</p>
        <p><i>To display a different welcome page for this project, modify</i>
            <tt>index.jsp</tt> <i>, or create your own welcome page then change
                the redirection in</i> <tt>redirect.jsp</tt> <i>to point to the new
                welcome page and also update the welcome-file setting in</i>
            <tt>web.xml</tt>.</p>
    </body>
</html>